{% set name = "git-delete-merged-branches" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ca369e5f10c6027813432180cdbb5a7d644cee4d30e4ee2d6ff483a343df2222

build:
  entry_points:
    - git-delete-merged-branches = git_delete_merged_branches.__main__:main
    - git-dmb = git_delete_merged_branches.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools >=38.6.0
    - python {{ python_min }}
  run:
    - colorama >=0.4.3
    - prompt-toolkit >=3.0.18
    - python >={{ python_min }}

test:
  imports:
    - git_delete_merged_branches
  commands:
    - pip check
    - git-delete-merged-branches --help
    - git-dmb --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hartwork/git-delete-merged-branches
  summary: Command-line tool to delete merged Git branches
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
