{% set name = "git-delete-merged-branches" %}
{% set version = "7.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 44a4ae5a83f194f0800e373519fd22c6bb3e6e99b883221f7b666bd36cdac415

build:
  entry_points:
    - git-delete-merged-branches = git_delete_merged_branches.__main__:main
    - git-dmb = git_delete_merged_branches.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools >=38.6.0
    - python >=3.8
  run:
    - colorama >=0.4.3
    - prompt-toolkit >=3.0.18
    - python >=3.8

test:
  imports:
    - git_delete_merged_branches
  commands:
    - pip check
    - git-delete-merged-branches --help
    - git-dmb --help
  requires:
    - pip

about:
  home: https://github.com/hartwork/git-delete-merged-branches
  summary: Command-line tool to delete merged Git branches
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
